#!/bin/env sh

in_dir="svg"
build_dir="build"
out_file_format="png"
in_size="128"
out_size="128"

# create $build_dir if it doesn't exist yet
[ ! -d "$build_dir" ] && mkdir "$build_dir"

[ -n "$1" ] && out_size="$1" && echo "Switching to the output size: $out_size" >&2

mogrify \
	-background none \
	-density $(( out_size * 1500 / in_size )) \
	-resize "${out_size}x${out_size}" \
	-format "$out_file_format" \
	-path "$build_dir" \
	-print "Converted %t to $out_file_format\n" \
	"$in_dir"/*.svg
